### ISSUE TITLE
Problems Installing - Reboots at 79% Installed

### ISSUE THREAD

**Issue by ThongSong7** [THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH#12]
Great achievements thus far!  

While I was shopping and investigating around for an UMPC, I came across this repo - which led me to chose the little guy.  I have the 512GB/16GB version, luckily the 512GB was already in SSD attached.

I have been hackintoshing since Apple went over to Intel back I think back on Tiger so I have been in the scene a long time - the installation/kexts have evolved massively and it is heart warming to see the growth of the community.  

Long story short.  I made my own Catalina USB (Kingston 16GB USB3) via my other Hackintosh - installed the latest clover on the USB and then copied your EFI files like you suggest.  This ends up in me being able to install to the HDD HFS+ Primary Partition up until about it looks like around 80% and then Black screen and reboot.

I changed the OS from that of the USB Image from Olarila (per your link) - ethched to same USB as above, changed the EFI/Clover files with yours and same procedure.... reboot at around 80% of installation.

I have tried using the USB on the other port (USB2) it just installs slower but again reboots at 80%.

I have not yet flashed the BIOS to the Modded one, maybe I should - I HAVE flashed the BIOS version on the CHUWI forums that helped the Fan to be only on when over 66 Degrees, could THIS be a reason why or a clue?

Didn't wanna open an issue, moreover just a shout out for help.  Not sure where to go from here, do you have any suggestions to assist me in getting the installation past 80%

Thanks for your diligence and help.

**Comment by balopez83** [comment]
Hi @ThongSong7 welcome to the MiniBook community. So I have two questions and then recommendations based on what I think might be going on. 
1) Are you using the 4K config file on you locked UEFI/BIOS?
2) Did you wipe the SSD and are attempting to install macOS first or have you left the factory install and simply added a partition for macOS?

Recommendations:

* You may use the existing partition from the Chuwi but you need at least 200mb for the SSD's EFI (it will cause problems if its the usual 100mb that comes with it). While a pain you can use Ubuntu to resize and adjust your partitions to increase the EFI size. I recommend at least 300mb for the EFI
* It may be easier to simply reinstall your Windows partition if you are going to keep windows installed (windows sometimes makes some odd partition maps though) 
* Personally I installed macOS as the first OS and then installed Windows using BootCamp (requires you to use OpenCore)
* If you reinstall Windows you should export your drivers before you wipe the SSD as there are three drivers you need to reinstall for the computer to work properly (fingerprint, wifi, goodix touch), You may update the wifi driver after but you should install the wifi one first as it has been customized.
* I recommend of course backing up your SSD before you wipe the SSD if you do. Macrium Reflect has a free program that works great for taking an image of your SSD.

Instead of following the directions for install from the readme (needs to be updated), follow these steps.
1. make a new installer from the AppStore and then use something like DiskMakerX or the like to create your usb
2. Instead of creating your own EFI or following the previously linked directions, copy one of the EFI's from the Releases page (don't use the GitHub files as they are still being tested and may have bugs). Place the EFI on your boot disk. You may use either the Clover or the OpenCore EFI for your installer boot disk though Clover is loosing support and so far does not have any official support for Big Sur. OpenCore takes a little getting used to but currently OpenCore configurator can be used and can make the transition easier. 
3. Select the appropriate config file and name it config.xml. If you have unlocked your bios or have performed the modded grub edit of the bios code and enabled DVMT of 64mb you may use the 4K config file. If you have not yet done that you must use the 1080p config file or you won't boot.
4. [Optional] Go ahead and fix the iMessage settings by adding your serial information in the config file and validating it
5. Boot to your USB and begin installing. You should now be able to finish the install and reach the desktop
6. Copy the EFI from the USB boot disk and install to your SSD

**Comment by ThongSong7** [comment]
Thank you for all of your assistance!

- It had to do with the Formatting of the HDD and SecureBoot
Catalina does not want MBR formatted partitions and will only (?) install onto APFS (GUID) so therefore should use SecureBoot. 

I had disabled SecureBoot for my Fedora32 Installation before.  I suppose now I will be using Boot Camp :)  

Here is what I did (for what it is worth to others?)
## Think out of the box ##
Clean HDD - Formatted in APFS Journaled GUID
Rebooted
Enabled SecureBoot
Cleaned all Known Keys in BIOS
Enrolled Cloverx64 EFI (on USB)
Booted Installation Disk (USB)
Installed to new Disk  
It rebooted AGAIN at around 80%
Reboot (this time via USB still connected) but chose new HDD
It automatically ran the FileVault (not sure of name) script
Rebooted automatically
Booted again from new HDD
WELCOME SCREEN to setup :)
Installed Clover on HDD
Copied over your EFI files
WORKS! 

Thanks again!  So awesome to have MacOS running on this little baby!
