### ISSUE TITLE
Clamshell Mouse Issue

### ISSUE THREAD

**Issue by ThongSong7** [THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH#17]
When the device is placed in "Clamshell" meaning the device's lid is closed while connected to an external monitor either via HDMI or USB-C Hub to HDMI (still using internal Intel Video card) something is still active hardware-wise to make the (connected mouse, USB-C or via HUB) not work and be 'pinned' to top left of external monitor and not allowing any movement or control via other mice/keyboard attached.  Sometimes it will even 'click' something under the mouse itself, this has lead me to think that it is the small mouse, but it could also be the "touchpad" i2c Voodoo touchscreen which is in contact with something physical?

Workaround is to place a thin piece of paper or cardboard in between the lid and bottom of case while closed.  Enough to make the Chuwi think it is closed(?) i.e. internal monitor off and full GUI to external Monitor while allowing full control via other plugged-in HIDs. 

Could this be that the mouse is touching the internal screen of the Chuwi and getting input, meaning the mouse is not dis-activated while lid closed in "Clamshell" and the paper in-between the closed lid and case act enough that the mouse does not 'touch' the screen?

Not sure about the idea above, because if I place the Chuwi horizontal on its back (fan exit) and remove the paper - all is normal - if placed flat as normal then the problem comes back...  Something is very sensitive - any ideas?  Sometimes I can place it back flat and it work, while other times I must use the paper-trick.

Not sure, however the paper trick works ... could we try to disable the mouse/touchscreen when lid closed and in clamshell?  

Anyone have this experience too?

**Comment by balopez83** [comment]
Hi @ThongSong7 thank you for reporting the issue. The issue you are referring to is a touch screen issue where it is not aware that the screen has been closed and so keeps the touch panel active. As of the Stable Release 1.0.0 there is code that does disable both the keyboard and the trackpoint when the lid is closed so that won't add to this issue. 

While I will explore ways to disable the touch screen via the SSDT patch I am honestly not very optimistic. I believe the only way for this to be fixed is for the touch driver itself to be updated and for it to implement power saving functionality that will be able to turn off the touch panel when the screen is off. 

As of right now the Goodix Touch project has been stalled as the owner has been pulled in other directions. As a result pending additional contribution of know how it is likely that the driver will not work after Catalina anyway as it is not supported in Big Sur.

Since this issue is related to that kext I would recommend adding an issue to the VoodooGoodix Github page so that the issue can be tracked and followed up with there.

**Comment by ThongSong7** [comment]
Thanks for the follow up, I understand the hurdles more now.  

Strangely enough, I am using your EFI version 1.0 (OC) but still seeing the problem.  

Just yesterday I left my device, came back a couple of minutes later to see about a hundred new folders on the desktop (because I was not using the cardboard trick)!  If there is code to disable the touchscreen when the lid is closed, one could assume that this behavior would not be happening.  

I am only posting this as I feel this is a 'bug' problem, but if I need to carry around a piece of cardboard, I am willing to do so :)

Regardless, keep up the outstanding work! :)

**Comment by balopez83** [comment]
Hi @ThongSong7 I understand you are having an issue still but I should clarify what is going on with it. 
While there is code to disable the touchpoint and keyboard, this code does not have any connection with disabling the touch screen panel. 
What I was actually saying is that the issue you were referring to used to be worse when the touchpoint was still active and the last release reduces but does not stop the problem your are referring to. 
Unfortunately, the issue is 100% caused by the voodooi2c kext not powering off due to missing power management features which is not within the scope of this project. 

While I understand why you believe it should be filed as a bug here, since this bug is beyond the scope of this project the kext will not be worked on here. Thus filing the bug here wont notify the kext owner, and the bug won't actually be resolved. This is why I mentioned reporting the issue on that GitHub page so that it can be looked into. In fact, because the touch kext does not work in OC 0.6.1 or later and does not work in Big Sur, the kext may end up being removed in later releases anyway.

In the short run, since it seems like you are using your Minibook as a desktop more than a laptop you can actually just permanently disable the touch kext. If you open the config plist and change "True" to "False" under VoodooGoodix.kext; reboot; you will then have your touch screen disabled which will prevent your issue. While this will solve your issue you of course will not have your touch screen working anymore even after rebooting until you switch the kext back on in the config file.

Hope that helps clarify a little and solve your issue.

**Comment by ThongSong7** [comment]
Thank you for clarifying the issue.
