### ISSUE TITLE
Some troubles on install.

### ISSUE THREAD

**Issue by kobzar** [THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH#18]
Hi 2 all. 
Sorry for some simple question but i cant understand where i am missing. 
First, i was create usb boot stick with OpenCore. 
Next i was copy all files from this repo to EFI partition on my stic. 
Next, i am booting from usb stick and install the OS. 
But WiFI device isn't present and i can't rotate the screen (doesn't have this option)
Maybe i must add some Kext to EFI partition? 
It this is true - why you don't add it by default? 
Thanks.

**Comment by ThongSong7** [comment]
For the Screen Rotation, on the 'Code' frontpage we get this:

"Changing the display orientation
To correct the screen orientation within macOS download the Display Rotation Menu app and set the view to portrait flipped OR press and hold down cmd+opt (Windows+alt) and open System Preferences...keep holding down those two buttons and click on Displays then the rotation option will appear so set it to 270 degrees for the fixed layout"

Because our devices are a bit strange on the rotation, we need to have it at 270 degrees to be landscape because 'normal' is at 90 degrees.

For the WiFi, you will need the application which is linked again from the frontpage:
https://github.com/1hbb/OpenIntelWireless-Factory/releases

This will be the up-to-date kernel extension and Application, you will need to overwrite the Kernel Extension (OC: /EFI/OC/Kexts/) with the updated one and overwrite the HelioPort Application (if already present) which controls the Wireless.

I hope this has helped get you connected.  If so kindly mark this issue as resolved :)

**Comment by kobzar** [comment]
Thanks for the quick answer. 
In last time when i try to install os X as secondary OS i was broken my EFI partition. 
So, i want to understand at this point before i will try again:
At this moment i have 4 partition on my own hard drive. 
1 - 100MB EFI
2 - 400GB - main windows 
3  -1G - windows restore
4 - like a 72GB - free for mac os. 
So, after i'll installed os X on 4 partition, next booting from usb stick and run os X i must download OC and install it from mac os to 1 partition? Or i just can copy all from this OC-EFI files to my 1 partiion? 
I'm afraid to stuck again %)

**Comment by balopez83** [comment]
Hi @kobzar, you need to make some adjustments to your partition layout in order to install macOS. While you might be able to install without making a change to the EFI you may likely run into issues where it won't install or future updates could fail as macOS likes to put a very large Apple folder in the EFI which exceeds the space available. You have three choices; 1)  You can either resize your EFI partition to at least 200mb. This can be done with a Ubuntu live USB disk and Gparted. 2) you can copy the OC EFI folder to the EFI partition and HOPE you have enough space if you didnt resize it. 3) You can create a second EFI partition in your 72gb free space before installing macOS where you would store only your OC bootloader. If you choose this option you will need to make sure you select the appropriate boot option in the BIOS/UEFI otherwise it will still try and boot to windows. 

If you are not planning or wanting to reformat and reinstall everything on the computer like most people end up doing then Option 3 would likely be the easiest for you. Option 2 is the least preferred. 

Also macOS should be installed to a single APFS partition which it will format the partition to during installation. So long as you create the 72gb partition as NTFS and then reformat it to HFS+ in the macOS installer then you will be fine. Be careful not to accidently format your other partitions or you could loose Windows or the ability to boot to Windows.
