### ISSUE TITLE
Fan Speed Still Loud?

### ISSUE THREAD

**Issue by thetomcraig** [THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH#19]
Hey, thanks for putting together this guide! I just finished an install and it was super clear and helpful.
Things on my minibook are working as expected, expect for the fan... It's still pretty loud, even when activity monitor shows very little going on.

I saw the comment here: https://github.com/THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH#the-fan-does-not-work-on-its-own-and-requires-a-special-patch-please-use-efi-release-version-010-or-higher-to-enable-automatic-fan-operation, if I understand correctly this means there should not be any additional work to get the fan working, after installing the EFI folder in this repo.  Is that correct?

**Comment by balopez83** [comment]
Hi @thetomcraig I am glad the guide and EFI is working well for you. Yes you are correct in regards to the fan. The fan should operate based on the temp of the proximity sensor of the CPU rather than the CPU core temps as is reported in HWMonitor or iStats. 

The result of this and the way we had to implement fan control for macOS is a lot different then how it works in Windows. In a nutshell what we have done is bypassed the EC standard control since its not supported due to some programming shortcuts taken by Chuwi and so it may at times seem that the fan operates faster then you would expect at certain times. What you should expect is that the fan will operate faster at lower temps then Windows but will spin down to the lowest speed the fan is programmed with when the proximity sensor drops to 49 deg Celsius or lower. During start up for the first 5 minutes however the EC is handling a lot of tasks and so you may find the fan won't drop to its lowest setting as quickly and also may take longer to speed up as well. 

If you are noticing that the fan is running high all the time. You likely are experiencing issues with heat dissipation which is related to the small design of the computer. You may want to look into the thermal and fan mods as described in the Minibook forums on Facebook or possibly the EC fan mod which is found on Chuwi's forums which with my fan patch in the EFI will actually turn off the fan when the Minibook reports 49 deg Celsius or lower. 

Unfortunately, the MiniBook's stock fan is cheap and so tends to be loud anyway. Since the fan is programmed to never turn off by default a lot of people have complained about the noise. Also, the fan makes noise when you move the computer due to cheap bearings and so it all can be quite annoying. If you are technical enough to attempt it, I would perform the thermal, fan, and EC mod which will make for about a 10-20 deg cooler machine and significantly quieter. 

Hope that helps a bit, and hope you enjoy using macOS on the MiniBook

**Comment by ThongSong7** [comment]
I wanted to chime-in also to confirm that modifying the EC via the patch found on the CHUWI Forum + changing the physical fan + changing thermal putty equals a VERY nice and "cool" minibook!   Granted we have the power of a large computer compressed into a small space, so do not expect there to NOT be any heat dissipation, because there will be, but enough to be bearable.

Another point to help would be undervolting the m3-8100Y, for me the maximum is -75/-75/-75 without freezing, YRMV though.   Look into VoltageShift for MacOS...

**Comment by thetomcraig** [comment]
Wow thanks for the thorough responses guys!  Very much appreciated :).  Will be looking into the EC patch and fan replacement.  VoltageShift sounds interesting as well... Thanks again!
