### ISSUE TITLE
Battery Level not working (in version 1.0.0)

### ISSUE THREAD

**Issue by ThongSong7** [THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH#20]
I am so very happy with the implementation that you have brought to our MiniBooks, the OS is working wonderfully on it thanks to your diligence and hard work!  

I know that before the 1.0 the battery level was working (for the most part), meaning that it would read out different levels other than 100%, but now both Clover or OC of version 1.0 are only showing 100% (when on charge) until it violently shuts off because of a lack of power.  When charging though it seems to read out different levels...  This is with both the OS Battery Meter or iStat Battery Meter...

Is there anything that I can do to get a working battery meter for the device?  Should I need to change something in the BIOS?

Thanks in advance for your help :)

**Comment by balopez83** [comment]
Hi @ThongSong7, I am glad you are enjoying the MiniBook and macOS. Unfortunately, the issue you are experiencing is a known problem with the MiniBook battery. Chuwi used very cheap batteries with controller chips that fail as quickly as a few weeks but never more than a few months. 

Now that your battery is only showing 100% except when charging after it dies on you, you need to be careful as your battery will likely begin to swell and damage your MiniBook. I recommend looking online on AliExpress for an aftermarket battery. The aftermarket batteries are significantly better and do not have the same issues. They also are a little higher capacity even though they are not sold as being higher capacity. 

The link I used to buy a battery to replace my defective battery unfortunately no longer works but several vendors are selling them. If you order a battery its likely you will get the battery in a week or two. 

Sorry again for the bad news but definitely get the battery replaced as soon as possible and you will be better off. Chuwi also is doing battery replacements but they use the same defective battery so I dont recommend going that route

**Comment by THEDEVIOUS1** [comment]
reopened to see if the same method that worked for me will work for u although the advice @balopez83 gave u about getting a backup battery isnt a bad idea and probably the best bet....with that said try these things in this order.
 
1.  turn off the unit then let the battery charge until the light turns blue/u thinks its full(typically 2 hours i believe). 
2. unplug the charger and open the bottom and disconnect the battery then hold the power for 45 seconds(this is the procedure recommended by chuwi themselves to do an ec reset although i think they say only 15/20 seconds or so). now...if your minibook behaves the same as mine then it will now be showing 0% (instead of 100%) the entire time but will in fact be fully charged
3. completely deplete the device again then repeat the ec reset procedure (step 2) i just stated above(play a movie or game to kill it quicker)
4. leave the device powered off then connect the adapter and let the device charge up until the power led turns blue again

although it may take almost 8 hours to do, if this all went well your battery should now be working perfectly as these are the exact steps i followed when i was having the same situation...i have a theory(although admittedly lil actual proof) that the swelling is due to the battery being overcharged because the level is misreported and the above procedure prevents that(hopefully anyway). while its POSSIBLE that if the device is already full u could skip step 1(if its reporting 100 percent all the time u wouldnt really know though) and if its completely drained then u could skip both steps 1 and 2 but i would recommended against it...ive explained things exactly the way that has my own personal device (that im typing this on) working as wanted

**Comment by ThongSong7** [comment]
Thanks for the extra steps!  

To add here that if you have already set your pre-allocated FB memory to 64MB for 1080p, then you'll need to set it back to that since this resets the BIOS also.

Mine was at 60% after this even though I left it charge for about 3 hours!  BUT it started to go down little by little - corrected?  We'll see.

I will do the rest, drain to 0% and then do the reset again.  Already to see it deminsh correctly (even though quickly) is a good sign!

If anything, I'll get a replacement if this is not going to work...

I will go ahead and close this issue, but thank you again for the extra assistance!

**Comment by ThongSong7** [comment]
@THEDEVIOUS1 :
I wanted to thank you, I did as you suggested and my percentage is there now - it seems to be stable, meaning that it is representing accurately draining and charging values.
