### ISSUE TITLE
Compatability Question

### ISSUE THREAD

**Issue by ThongSong7** [THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH#21]
Great job!  Excellent work, especially being able to get Goodix working with BigSur - OUTSTANDING!  

My question is about the compatability for the OC EFI Files.

On the frontpage you have added:
"- OpenCore Release Version 1.2.0 and above should be used for macOS Big Sur and above."
however on the latest Stable release you have:
"Stable v1.2.0-OpenCore (OS: 10.15-11.X.X)" - which Catalina (10.15.7) fits into this category

Am I able to use the 1.2.0 version on 10.15.7?  If so what changes do I need to make for it to boot properly?

Thanks in advance and my apologies for the confusion.

**Comment by balopez83** [comment]
Hi @ThongSong7 I understand why that may lead to some confusion and happy to answer. 

Basically, there is some overlap in the support the EFI versions provide. EFI version 1.2.0 technically could boot an OS as low as Mojave BUT this particular release contains kexts for WiFi that are targeted for any OS version Catalina and newer. EFI release 1.1.0 and below contain kext's that are more generalized that support a greater number of older OS versions but fail to work properly on the latest OS's.

The reason the Readme states users of Big Sur should use 1.2.0 is that you will find greater native support and the greatest features including built in WiFi and touch support in 1.2.0 and up that don't exist in 1.1.0 or below even though you could technically boot Big Sur with say an EFI version 1.0.0 or possibly even older. 

I would definitely recommend a user to use 1.2.0 to boot any release version of Catalina and should be able to do it without any changes or issues for any version as low as 10.15.0

Personally, I am using 1.2.0 to do final last minute testing on Catalina before moving completely over to Big Sur. Nothing special should be needed to make it run other than my recommending that you clear NVRAM just to make sure there is no glitches.

**Comment by ThongSong7** [comment]
@balopez83 : Thank you for the explaination, are there any additional steps that one must do to start using OC 0.6.2 in your 1.2.0 version?  

I have copied the entire EFI folder (with its subfolders) to the EFI partition as I have done in the past with your updates, however this time on boot it gives a few errors about drivers?, shows the icons (this time only the clearNVRAM addtition) and it reboots then directly to Recovery Mode.  Retry - ClearNVRAM - Boot to HDD OS - Recovery.  

Am I doing something wrong?  I have done it like this since your 1.0.0 EFI Files

In order to get my OS back, I needed to terminal delete and copy over a lower version to EFI.

OC Config files are capital now, intended?  Maybe this is indeed intended to seperate the versions?

Edit:  Not sure if case-sensitivity is an issue, but the config files do start with a Capital 'C'.  Also, there is note of Secure Boot (SB) issues in the front-page ReadMe, should it (SB) be activated/disabled?  Should we need to enroll the efi files responsible for booting OC 0.6.2 for SB?

Thanks again for your help.

**Comment by balopez83** [comment]
Hi @ThongSong7 , I believe I know what the issue is with the driver errors at initial OpenCore start up and will look to fix that issue and re-upload 1.2.0. 

Your boot issue is a little weird though as it should boot fine but depending on what OS you are booting it certainly could have an issue I was not aware of. What version of OS are you using? Be specific as in example: are you using Catalina 10.15.7, Big Sur Beta 10, Big Sur Beta 11.0.1, etc. 

If you are using Beta 10 or Beta 11.0.1 your issue actually doesn't surprise me and is related to secure boot which will need to be turned off in order to boot. If this is your situation then once secure boot is off wifi will no longer work and you will need to install it to /L/E/ which is not recommended at this time. If this is your issue I would actually recommend using the old EFI that did work for you and then waiting until the next EFI release 1.3.0. If you are using Catalina, I will need to test it again and see if I can duplicate your issue and fix it prior to re-uploading the release.

Its likely I will need to change the supported OS versions as due to changes in the Big Sur betas 1.2.0 with OC 0.6.2 is no longer well supported. I will be releasing a new EFI release 1.3.0 with the official OC 0.6.3 which should resolve all issues with Big Sur and should support the official release of Big Sur once it is released.

As for secure boot, I should clarify that while the name is the same its not related to Secure Boot of the same name in your UEFI/BIOS. Instead its in relation to the macOS file system and the way it securely boots using OpenCore. As such no registration is needed and no changes would be needed in your UEFI.

**Comment by ThongSong7** [comment]
I am running Catalina 10.15.7 with your 1.1.0 working well.

**Comment by balopez83** [comment]
Hi @ThongSong7 , I have re-uploaded the EFI with the config file fixed to prevent those errors from appearing on OpenCore startup. 

I was unable to duplicate your issues booting while also booting from Catalina version 10.15.7. 
I suspect you might need to try again but make sure you clear NVRAM.

I have recently discovered that large partition sizes impact system start up and can take as long as 2.5 minutes. If you have a large partition size greater than 500GB your system may appear frozen but if you wait it should still start up. I have not yet figured out why this is happening but I am working on that. Not sure if this is part of your current issue but assume its not since I think you said you had an NVME and it is an issue I confirmed happened with Release 1.1.0 which you said worked fine for you.

**Comment by ThongSong7** [comment]
@balopez83, the changes that you made to the 1.2.0 do seem to get rid of the small errors at boot, however I am still not able to get into the OS (Catalina 10.15.7).  Upon reboots it will go directly to Recovery OS.  

Possibly to assist you:
I **AM** however able to boot and use your BETA 1.3.0.  There is about a 6 to 8 second wait at the Apple logo for the progress bar to show and then advance. To date, I have not seen this stage take up to this amount of time.
Could this be a small change in the 1.2.0 version, a timeout set too low?  

My SSD is 512GB formated in APFS with 200MB EFI, so large disk should not be the issue.

Otherwise I suppose that I'll have to 'live on the edge' and use your Beta Version to profit from the integrated WiFi (quite nice!) et al.  So count me in as one of your 'Beta' Users for now for when you make changes and need another perspective/approval/confirmation.

**Comment by balopez83** [comment]
Hi @ThongSong7 if you have not yet already, go ahead and update to Release 1.3.0. 

The Release resolves a LOT of issues related to 1.2.0 and specifically OC 0.6.2. You should experience a significantly better experience. Some things you should be aware of though; you may still get kicked to recovery after clearing NVRAM but after selecting OC as your default boot option and possibly after a second reboot you should be good.. I think this has to do with computers that have windows installed as primary. If you reinstall everything like a proper mac with macOS primary and then installing windows through bootcamp you shouldnt have that issue

**Comment by balopez83** [comment]
If your issue is now resolved go ahead and close this issue. If you're still having issues let me know

**Comment by ThongSong7** [comment]
The update is working wonderfully.  Thank you for your diligence!
