### ISSUE TITLE
Charging and battery status indication incorrect

### ISSUE THREAD

**Issue by lazd** [THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH#8]
I've had the laptop die on me a few times when it read almost 70%, then, on restart, showed 3%.

I've also seen it show that it is plugged in when its not. I wonder if this is a BIOS configuration issue or something, because I've had Windows die on me during gaming without popping up a warning (I'm not sure if it's supposed to when apps are full screen, so I can't be sure).

If others have experienced weird power issues, please report here.

**Comment by lazd** [comment]
According to @hatran0884, this is fixed by updating the EC. Instructions are here: https://forum.chuwi.com/t/topic/3282

**Comment by kostaskas** [comment]
I have run that command on windows: **powercfg -setdcvalueindex SCHEME_CURRENT SUB_BATTERY BATACTIONCRIT 0** to disable actions when critical battery status reached. That way I drain battery till minibook shuts off at 0% battery. Then fully charged it without opening it and battery meter seems fixed.

I had already done EC upgrade due to fan disabling when temperature is low, info found [here](https://forum.chuwi.com/t/minibook-ec-patch-fans-turn-off-now/4678/8)

**Comment by lazd** [comment]
@kostaskas flashing EC didn't fix the issue to me, but I will try the Windows command tonight.

**Comment by kostaskas** [comment]
yes try it to drain battery completely, leave it until it shuts-off, then fully charge it without switching-on the minibook

In my opinion, I thing the bug has to do with BIOS, all chinese tablets, PCs etc have BIOS bug that have to do with power, I had two tablets with issues like that, especially booting between OSs may trick EC

**Comment by balopez83** [comment]
Resolved with Release 0.1.0 to be posted this week. If you continue to have issues after completely replacing your EFI with this release please either re-open or create a new ticket.
